### ISSUE TITLE
Failed to activate the atom-htmltidy package

### ISSUE THREAD

**Issue by avk** [AnWeber/atom-htmltidy#1]
Steps to reproduce:
1. Open raw .html file in Atom. Can't provide my specific file for privacy reasons.
2. Open Command Palette.
3. Select atom-htmltidy.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-htmltidy](https://github.com/AnWeber/atom-htmltidy) package, v1.1.0
### Stack Trace

Failed to activate the atom-htmltidy package

```
At unsupported execution platform

Error: unsupported execution platform
    at chooseExec (/Users/avk/.atom/packages/atom-htmltidy/lib/tidywrapper.js:149:13)
    at Object.<anonymous> (/Users/avk/.atom/packages/atom-htmltidy/lib/tidywrapper.js:22:16)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/avk/.atom/packages/atom-htmltidy/lib/init.js:9:20)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:14)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:166:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:738:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:12.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:05.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:03.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 atom-htmltidy:format (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "whitespace"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-htmltidy, v1.1.0
atom-jasmine, v0.8.1
copy-path, v0.2.1
file-icons, v1.6.12
html-entities, v0.4.0
jshint, v1.8.3
jsonlint, v1.1.2
language-babel, v2.5.2
language-haml, v0.23.7
language-rspec, v0.3.0
linter, v1.11.3
pigments, v0.19.1
react, v0.12.10
rspec-snippets, v0.4.0

# Dev
No dev packages
```

**Comment by AnWeber** [comment]
Hello,

In current release Mac OS X is not supported. I will try a blind shot to
support it in the next release. Please try again.

Thanks.

Arthur Klepchukov notifications@github.com schrieb am Mo., 7. Dez. 2015
20:32:

**Comment by avk** [comment]
Damn sorry to hear that. Happy to try it when it is. Can you please indicate that in the main README so others aren't similarly confused?

**Comment by AnWeber** [comment]
I made the change to support Mac OS X. New Version 1.2.0. Please give it a try. If it doesn't work, you can try to set a own tidy exec in the settings. If you got a valid setup, please provide me with the details.

thanks for your help.

**Comment by AnWeber** [comment]
I made the change to support Mac OS X. New Version 1.2.0. Please give it a
try. If it doesn't work, you can try to set a own tidy exec in the
settings. If you got a valid setup, please provide me with the details.

thanks for your help

Arthur Klepchukov <notifications@github.com> schrieb am Mo., 7. Dez. 2015
21:09:

**Comment by antony** [comment]
Atom appears to be throwing this exact same error on Ubuntu Linux. Can the same fix be applied?

**Comment by AnWeber** [comment]
Please tell me the [process.platform](https://nodejs.org/api/process.html#process_process_platform) of ubuntu linux. With the current release the platforms win32, darwin  and linux are supported. Unfortunately Ubuntu returns some unknown value.
There is a workaround you can use in the mean time. Configure a valid tidy executable in the settings of my package (setting 'path to tidy executable'). You will find a executable in my package under ".atom/packages/atom-htmltidy/lib/bin/linux"

**Comment by antony** [comment]
Hi, what do you mean by process.platform? Where can I find that information?

**Comment by AnWeber** [comment]
Hi, please perform command window:toggle-dev-tools in atom. Then enter
process.platform in the developer console. Thanks

Antony Jones notifications@github.com schrieb am Di., 19. Jan. 2016 um
21:45 Uhr:

**Comment by antony** [comment]
process.platform
"linux"

Looks like it should be ok... but it isn't.

**Comment by antony** [comment]
Also, I'm trying to set a manual path to htmltidy, and there aren't any settings?

For other packages settings exist, but for atom-htmltidy, I can only see 'readme'.

**Comment by AnWeber** [comment]
hello, sorry for the long delay. I have installed ubuntu 15.10 in a virtual machine. I verified the missing settings. Maybe you could set the settings directly in the settings.cson. But I will try to fix it [Issue 6](https://github.com/AnWeber/atom-htmltidy/issues/6) 
In my installation I couldn't reproduce the error. My test.html was formatted like I would expect it. Did you see a warning with the message 'Unsupported platform. Please configure own tidy executable'?

**Comment by antony** [comment]
Hi, I didn't see that message. I'll screenshot the error I got when I try again shortly.
